# Jekyll configuration

name: connorbashamfitness-com-au
description: Connor Basham's fitness website
author:
  name: Mike Causer
  email: mcauser@gmail.com

url: http://connor-basham-fitness.github.io/connorbashamfitness-com-au

exclude: [".ruby-version", "Gemfile", "Gemfile.lock", "README.md"]

sass:
  style: compressed

encoding: utf-8
